### ISSUE TITLE
How to create and run an Android emulator on the build system?

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#19]
I'm trying to create an Android emulator using `avdmanager` and [this guide](https://developer.android.com/studio/command-line/avdmanager). The sample YML script is:

```
image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - $ANDROID_HOME/tools/bin/avdmanager create avd -n Android_7.1_API_25 -k "system-images;android-25;google_apis;x86_64" -c 250M --abi google_apis/x86_64
```

But it just results in the following error and stops the build:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.checkBounds(String.java:381)
	at java.lang.String.<init>(String.java:545)
	at com.android.sdklib.tool.AvdManagerCli.readLine(AvdManagerCli.java:1110)
	at com.android.sdklib.tool.AvdManagerCli.promptForHardware(AvdManagerCli.java:983)
	at com.android.sdklib.tool.AvdManagerCli.createAvd(AvdManagerCli.java:817)
	at com.android.sdklib.tool.AvdManagerCli.doAction(AvdManagerCli.java:369)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:205)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:195)
Do you wish to create a custom hardware profile? [no] 
```

How do I workaround this? I eventually want to create and run an emulator on the Docker image.

**Comment by ozmium** [comment]
This can be done with a custom bash script. See Issue #18.
