### ISSUE TITLE
Can't get androidTests (emulator) working

### ISSUE THREAD

**Issue by goemic** [mingchen/docker-android-build-box#58]
Hi,

unfortunately I'm unable to make androidTests work. The emulator is starting/started but when calling `./gradlew connectedAndroidTest` (after almost 15 minutes), I get this exception:

```
...
> Task :app:connectedDebugAndroidTest
Task :app:connectedDebugAndroidTest in app Starting
Caching disabled for task ':app:connectedDebugAndroidTest' because:
  Build cache is disabled
Task ':app:connectedDebugAndroidTest' is not up-to-date because:
  Task.upToDateWhen is false.
DeviceConnector 'test(AVD) - 7.0': installing /opt/atlassian/pipelines/agent/build/app/build/outputs/apk/debug/app-debug.apk

AAPT2 aapt2-4.1.0-6503028-linux Daemon #0: shutdown
AAPT2 aapt2-4.1.0-6503028-linux Daemon #1: shutdown
AAPT2 aapt2-4.1.0-6503028-linux Daemon #2: shutdown
AAPT2 aapt2-4.1.0-6503028-linux Daemon #3: shutdown

> Task :app:connectedDebugAndroidTest
Unable to install /opt/atlassian/pipelines/agent/build/app/build/outputs/apk/debug/app-debug.apk

com.android.build.gradle.internal.testing.ConnectedDevice > runTests[test(AVD) - 7.0] [31mFAILED [0m
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException
		at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:136)
[XmlResultReporter]: XML test result file generated at /opt/atlassian/pipelines/agent/build/app/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/TEST-test(AVD) - 7.0-app-debugAndroidTest.xml. Total tests 1, failure 1, 
com.android.ddmlib.InstallException
	at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1230)
	at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1050)
	at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1026)
	at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1015)
	at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:130)
	at com.android.build.gradle.internal.testing.SimpleTestRunnable.run(SimpleTestRunnable.java:134)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:68)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.externalInterruptibleAwaitDone(ForkJoinTask.java:361)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1001)
	at com.android.ide.common.workers.ExecutorServiceAdapter.await(ExecutorServiceAdapter.kt:102)
	at com.android.build.gradle.internal.testing.BaseTestRunner.runTests(BaseTestRunner.java:193)
	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.lambda$doTaskAction$2(DeviceProviderInstrumentTestTask.java:206)
	at com.android.builder.testing.api.DeviceProvider.use(DeviceProvider.java:53)
	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.doTaskAction(DeviceProviderInstrumentTestTask.java:194)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:74)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:34)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:57)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:726)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:693)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:554)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:537)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:278)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:267)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:598)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:381)
	at com.android.ddmlib.internal.DeviceImpl.executeShellCommand(DeviceImpl.java:711)
	at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1221)
	... 120 more
[no message defined]
Task :app:connectedDebugAndroidTest in app Finished
```
Do you have any advice?

Here is the script to start the emulator and execute androidTests:
```
#!/bin/bash

# Download an ARM system image to create an ARM emulator.
sdkmanager "system-images;android-24;default;armeabi-v7a"

# Launch the emulator in the background
# Create an ARM AVD emulator, with a 100 MB SD card storage space. Echo "no"
# because it will ask if you want to use a custom hardware profile, and you don't.
# https://medium.com/@AndreSand/android-emulator-on-docker-container-f20c49b129ef
echo no | avdmanager create avd --force --sdcard 100M --name test -k "system-images;android-24;default;armeabi-v7a"
emulator -avd test -no-audio -no-window &

## Wait for Android to finish booting
wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
chmod +x android-wait-for-emulator
./android-wait-for-emulator
## Unlock the Lock Screen
adb shell input keyevent 82

#start tests
./gradlew app:connectedAndroidTest --info
```

**Comment by felHR85** [comment]
@goemic 
Did you finally manage to get this working?

**Comment by felHR85** [comment]
I've managed to get my tests working with the following changes
Android image changed to 23:
` sdkmanager "system-images;android-23;default;armeabi-v7a"`

Increasing ADB_INSTALL_TIMEOUT variable:
`export ADB_INSTALL_TIMEOUT=30`

**Comment by ozmium** [comment]
Here are a few things to try:

1. After you run `./android-wait-for-emulator`, consider waiting for another 2-3 minutes before starting the tests in the next command. You can use a simple `sleep 180` command. When an emulator is created and started from scratch, it has to do many things when booting for the first time. It's like a factory reset of the device. The long wait is needed to allow the emulator to do these things, like connect to Wifi, initialize the SD card storage space, optimize all the pre-installed apps, start the Home Screen app, and so on. I assume that you see the error `com.android.ddmlib.ShellCommandUnresponsiveException` because emulator is still doing all these things and is not yet ready to install and launch external apps.

2. Try using an older Android OS version as your emulator, like Android 5 (API 21, 22) or Android 6 (API 23).

3. Try using the `-gpu off` flag when launching the `emulator` command. It's mentioned here: https://andresand.medium.com/android-emulator-on-docker-container-f20c49b129ef

Let us know if any of these suggestions worked for you.

**Comment by felHR85** [comment]
@ozmium 
Those suggestions are what I finally added to my script to get it working. I would also suggest to add the ADB_INSTALL_TIMEOUT that I mentioned previously to avoid the 2 min timeout that is the default timeout for ADB.

**Comment by ozmium** [comment]
@felHR85 Yes I agree 100%. Actually it's the first time I've ever heard of the `ADB_INSTALL_TIMEOUT` technique. So thanks for the insight. It seems to work for many people:

* https://blog.cyplo.dev/posts/2015/10/25/android-integration-test-timeouts/
* https://stackoverflow.com/questions/12573736/how-to-set-adb-emulator-timeout-from-commandline

Consider adding that info to this project's Readme file.

**Comment by nikhil-seth** [comment]
@felHR85  @ozmium  Can you share the updated script.
I tried this, but my docker/ bitbucket pipeline hangs on launching emulator

**Comment by felHR85** [comment]
@nikhil-seth  Where is your pipeline hanging?

This is the script that I am currently using with Bitbucket pipelines

```
#!/bin/bash

# ADB installation timeout needs to be increased
export ADB_INSTALL_TIMEOUT=30

# Create repositories if repositories.cfg file doest not exists.
touch /opt/android-sdk/.android/repositories.cfg

# Install Jenv(https://www.jenv.be/)
git clone https://github.com/jenv/jenv.git ~/.jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
source ~/.bash_profile

# Add Java 11
jenv add /usr/lib/jvm/java-11-openjdk-amd64
jenv local system

# Add sys image sources
echo "src01=https\://dl.google.com/android/repository/sys-img/android/sys-img.xml" | tee -a /opt/android-sdk/.android/repositories.cfg
echo "src00=https\://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml" | tee -a /opt/android-sdk/.android/repositories.cfg

# Download an ARM system image to create an ARM emulator.
sdkmanager "system-images;android-23;default;armeabi-v7a"

# Create an ARM AVD emulator, with a 100 MB SD card storage space. Echo "no"
# because it will ask if you want to use a custom hardware profile, and you don't.
echo "no" | avdmanager create avd \
    -n Android_API_24 \
    -k "system-images;android-23;default;armeabi-v7a" \
    -c 100M \
    --force

# Start emulator
$ANDROID_HOME/emulator/emulator -avd Android_API_24 -no-audio -no-window &
EMULATOR_PID=$!

# Wait until emulator is running
set +e

bootanim=""
failcounter=0
timeout_in_sec=360

until [[ "$bootanim" =~ "stopped" ]]; do
  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline" || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    echo "Waiting for emulator to start ${failcounter}"
    if [[ $failcounter -gt timeout_in_sec ]]; then
      echo "Timeout reached; failed to start emulator"
      kill ${EMULATOR_PID}
      exit 1
    fi
  fi
  sleep 1
done

echo "Emulator is ready"

# Unlock the Lock Screen
adb shell input keyevent 82

sleep 180

# DO YOUR STUFF (TESTS I GUESS)
TEST_STATUS=$?

kill ${EMULATOR_PID}
exit ${TEST_STATUS}

```

**Comment by nikhil-seth** [comment]
```
Task ':library:connectedDebugAndroidTest' is not up-to-date because:
  Task.upToDateWhen is false.
[DeviceMonitor]: Connected to adb for device monitoring
DeviceConnector 'Android_API_24(AVD) - 6.0': installing /opt/atlassian/pipelines/agent/build/library/build/outputs/apk/androidTest/debug/library-debug-androidTest.apk
AAPT2 aapt2-4.0.2-6197926-linux Daemon #21: shutdown
AAPT2 aapt2-4.0.2-6197926-linux Daemon #20: shutdown
AAPT2 aapt2-4.0.2-6197926-linux Daemon #10: shutdown
AAPT2 aapt2-4.0.2-6197926-linux Daemon #13: shutdown
----- End of the daemon log -----

FAILURE: Build failed with an exception.
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

```
It is unable install the apk. Daemon shuts down abruptly after some time.

**Comment by felHR85** [comment]
@nikhil-seth 
There are a couple of possible solutions in this SO thread. I hope this sheds some light. https://stackoverflow.com/questions/41684610/errorfailed-to-complete-gradle-execution-cause-gradle-build-daemon-disappear/44693275#44693275

**Comment by ozmium** [comment]
@nikhil-seth -- It could be a low-memory issue on your build machine, or a problem when using an emoji character somewhere. See:
* https://stackoverflow.com/questions/37171043/gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-hav
* https://github.com/gradle/gradle/issues/9371
* https://kenkyee.medium.com/yes-this-means-your-build-server-ran-out-of-memory-running-an-android-gradle-build-69bae138f94f
* https://stackoverflow.com/questions/46970018/docker-container-for-android-gradle-build-daemon-disappeared-unexpectedly-it

If possible, try to monitor the memory usage of your Docker container, regularly, and check which processes are using a lot of memory. Or perhaps try to increase the memory allocation of the Docker instance.

**Comment by nikhil-seth** [comment]
Thanks @ozmium  @felHR85 . It started working. Issue was with memory only. Added 2x in size & it worked perfectly.
