### ISSUE TITLE
Implement support of Apple M1 (Silicon)

### ISSUE THREAD

**Issue by Zaszczyk** [mingchen/docker-android-build-box#74]
Hi!
Could you implement support of Apple M1 processor? Now during running this image on such hardware I get error:

Command: `yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;30.0.3"`
```
 Exit status of command 'yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;30.0.3"' was 1 instead of 0.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by mingchen** [comment]
I donot have M1. I previous tried arm cpu and seems Android SDK not fully support arm yet.
If you make it work, PR is welcome.

**Comment by lukaspanni** [comment]
The container runs and builds android apps on my M1 machine without problems.
It's probalby a problem with your configuration @Zaszczyk.

**Comment by Zaszczyk** [comment]
@lukaspanni could you share your configuration?

**Comment by lukaspanni** [comment]
I used it exactly as stated in the documentation.
I also verified that it works with a newly created Android project. 
There is no additional configuration needed

**Comment by mingchen** [comment]
Build works on M1.
